spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: false
    change-log: classpath:db/migration/db.changelog-master.yaml
jwt:
  secret: B4qwFm2j63YqtS9IB4qwFm2j63YqtS9IB4qwFm2j63YqtS9I
  expiration: 3600000
card:
  encryption:
    secret-key: "B4qwFm2j63YqtS9I"